ProdTrace/Models/Classes/Invoice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ProdTrace.Models.Classes
{
    public class Invoice        //Fatura
    {
        [Key]
        public int InvoiceId { get; set; }

        [Column(TypeName = "Char")]
        [StringLength(1)]
        public string InvoiceSerialNo { get; set; }  //Fatura seri no

        [Column(TypeName = "Varchar")]
        [StringLength(15)]
        public string InvoiceSequenceNo { get; set; } //Fatura Sıra no

        public DateTime InvoiceDate { get; set; }

        [Column(TypeName = "Char")]
        [StringLength(5)]
        public string InvoiceHour { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(60)]
        public string InvoiceTaxAuthority { get; set; }  //Vergi Dairesi

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string DeliveryFrom { get; set; }  //Teslim eden

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string DeliveryTo { get; set; } //Teslim alan

        public decimal TotalPrice { get; set; }

        //Relationships
        public ICollection<InvoiceColumn> InvoiceColumns { get; set; }
    }
}

ProdTrace/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProdTrace.Models.Classes;

namespace ProdTrace.Controllers
{
    public class InvoiceController : Controller
    {
        // GET: Invoice
        Context c = new Context();
        public ActionResult Index()
        {
            var values = c.Invoices.ToList();
            return View(values);
        }

        [HttpGet]
        public ActionResult AddInvoice()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddInvoice(Invoice invoice)
        {
            c.Invoices.Add(invoice);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult GetInvoice(int id)
        {
            var value = c.Invoices.Find(id);
            return View("GetInvoice", value);
        }

        public ActionResult UpdateInvoice(Invoice invoice)
        {
            var values = c.Invoices.Find(invoice.InvoiceId);
            values.InvoiceSerialNo = invoice.InvoiceSerialNo;
            values.InvoiceSequenceNo = invoice.InvoiceSequenceNo;
            values.InvoiceDate = invoice.InvoiceDate;
            values.InvoiceHour = invoice.InvoiceHour;
            values.DeliveryFrom = invoice.DeliveryFrom;
            values.DeliveryTo = invoice.DeliveryTo;
            values.InvoiceTaxAuthority = invoice.InvoiceTaxAuthority;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult InvoiceDetail(int id)
        {
            var value = c.InvoiceColumns.Where(x => x.InvoiceId== id).ToList();
            return View(value);
        }

        [HttpGet]
        public ActionResult AddInvoiceColumn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddInvoiceColumn(InvoiceColumn invoiceColumn)
        {
            c.InvoiceColumns.Add(invoiceColumn);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ProdTrace/Views/Invoice/AddInvoice.cshtml
@model ProdTrace.Models.Classes.Invoice
@{
    ViewBag.Title = "AddInvoice";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Yeni Fatura Girişi</h2>
<br />
<form class="form-group" method="post">
    @Html.Label("Fatura Seri No")
    @Html.TextBoxFor(x => x.InvoiceSerialNo, new { @class = "form-control" })
    <br />
    @Html.Label("Fatura Sıra No")
    @Html.TextBoxFor(x => x.InvoiceSequenceNo, new { @class = "form-control" })
    <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.InvoiceDate, new { @class = "form-control" })
    <br />
    @Html.Label("Saat")
    @Html.TextBoxFor(x => x.InvoiceHour, new { @class = "form-control" })
    <br />
    @Html.Label("Vergi Dairesi")
    @Html.TextBoxFor(x => x.InvoiceTaxAuthority, new { @class = "form-control" })
    <br />
    @Html.Label("Teslim Eden")
    @Html.TextBoxFor(x => x.DeliveryFrom, new { @class = "form-control" })
    <br />
    @Html.Label("Teslim Alan")
    @Html.TextBoxFor(x => x.DeliveryTo, new { @class = "form-control" })
    <br />

    <button class="btn btn-primary">Kaydet</button>


</form>

ProdTrace/Views/Invoice/AddInvoiceColumn.cshtml
@model ProdTrace.Models.Classes.InvoiceColumn
@{
    ViewBag.Title = "AddInvoiceColumn";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Yeni Kalem Girişi</h2>
<br />
<form class="form-group" method="post">
    @Html.Label("Açıklama")
    @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
    <br />
    @Html.Label("Miktar")
    @Html.TextBoxFor(x => x.Amount, new { @class = "form-control" })
    <br />
    @Html.Label("Birim Fiyatı")
    @Html.TextBoxFor(x => x.UnitPrice, new { @class = "form-control" })
    <br />
    @Html.Label("Tutar")
    @Html.TextBoxFor(x => x.TotalPrice, new { @class = "form-control" })
    <br />
    @Html.Label("Fatura Id")
    @Html.TextBoxFor(x => x.InvoiceId, new { @class = "form-control" })
    <br />

    <button class="btn btn-primary">Kaydet</button>


</form>

ProdTrace/Views/Invoice/GetInvoice.cshtml
@model ProdTrace.Models.Classes.Invoice
@{
    ViewBag.Title = "GetInvoice";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("UpdateInvoice", "Invoice", FormMethod.Post))
{
    @Html.HiddenFor(x => x.InvoiceId)
    <br />
    @Html.Label("Seri No")
    @Html.TextBoxFor(x => x.InvoiceSerialNo, new { @class = "form-control" })
    <br />
    @Html.Label("Sıra No")
    @Html.TextBoxFor(x => x.InvoiceSequenceNo, new { @class = "form-control" })
    <br />
    @Html.Label("Vergi Dairesi")
    @Html.TextBoxFor(x => x.InvoiceTaxAuthority, new { @class = "form-control" })
    <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.InvoiceDate, new { @class = "form-control" })
    <br />
    @Html.Label("Saat")
    @Html.TextBoxFor(x => x.InvoiceHour, new { @class = "form-control" })
    <br />
    @Html.Label("Teslim Eden")
    @Html.TextBoxFor(x => x.DeliveryFrom, new { @class = "form-control" })
    <br />
    @Html.Label("Teslim Alan")
    @Html.TextBoxFor(x => x.DeliveryTo, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

ProdTrace/Views/Invoice/Index.cshtml
@using ProdTrace.Models.Classes
@model List<Invoice>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:20px;">
    <tr style="font-weight:bold">
        <td>ID</td>
        <td>Seri No</td>
        <td>Sıra No</td>
        <td>Vergi Dairesi</td>
        <td>Tarih</td>
        <td>Saat</td>
        <td>Teslim Eden</td>
        <td>Teslim Alan</td>
        <td>Toplam</td>
        <td>Güncelle</td>
        <td>Detaylar</td>
    </tr>
    @foreach (var d in Model)
    {
        <tr>
            <td>@d.InvoiceId</td>
            <td>@d.InvoiceSerialNo</td>
            <td>@d.InvoiceSequenceNo</td>
            <td>@d.InvoiceTaxAuthority</td>
            <td>@d.InvoiceDate</td>
            <td>@d.InvoiceHour</td>
            <td>@d.DeliveryFrom</td>
            <td>@d.DeliveryTo</td>
            <td>@d.TotalPrice</td>
            <td><a href="/Invoice/GetInvoice/@d.InvoiceId" class="btn btn-warning" style="color:white">Güncelle</a></td>
            <td><a href="/Invoice/InvoiceDetail/@d.InvoiceId" class="btn btn-default" style="background-color:lightcoral; color:white">Detaylar</a></td>
        </tr>
    }

</table>

<a href="/Invoice/AddInvoice" class="btn btn-info">Yeni Fatura Gir</a>

ProdTrace/Views/Invoice/InvoiceDetail.cshtml
@using ProdTrace.Models.Classes
@model List<InvoiceColumn>
@{
    ViewBag.Title = "InvoiceDetail";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Fatura Kalemleri Sayfası</h2>
<br />

<div class="heading mb-4" style="background-color:blueviolet; height:3rem;">
    <ul style="color: white; padding-top:10px; text-align:center;"></ul>
</div>

<table class="table table-hover">
    <tr>
        <th>Id</th>
        <th>Açıklama</th>
        <th>Miktar</th>
        <th>Birim Fiyatı</th>
        <th>Tutar</th>
    </tr>

    @foreach (var x in Model)
    {
        <tr>
            <th>@x.InvoiceColumnId</th>
            <th>@x.Description</th>
            <th>@x.Amount</th>
            <th>@x.UnitPrice</th>
            <th>@x.TotalPrice</th>           
        </tr>
    }

</table>

<a href="/Invoice/AddInvoiceColumn/" class="btn btn-default" style="background-color:darksalmon">Yeni Kalem Girişi</a>